# login, register, modify password
LOGIN_OK = "login_ok"
LOGIN_FAIL = "login_fail"
PASSWORD_ERROR = "password_error"
USER_NOT_EXIST = "user_not_exist"
USER_EXIST = "user_exist"
REGISTER_OK = "register_ok"
REGISTER_FAIL = "register_fail"
REGISTER_MAIL_SENT = "mail_sent"
MODIFY_PASSWORD_MAIL_SENT = "mail_sent"
IGNORE = "ignore"
CONFIRM = "confirm_ok"
